import os
import json
import logging
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from typing import Optional

import jwt
from fastapi import FastAPI, Depends, HTTPException, Request, Response, Form, status, UploadFile, File, Query
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from passlib.context import CryptContext
from sqlalchemy.orm import Session
from dateutil import parser as dateparser

from database import engine, SessionLocal, User, BreakdownLog, CAPA, CAPATask, CAPAComment, Equipment, Base
from api_routes import router as api_router
from utils import normalize_full_owner_string, clean_equipment_name

# ── Configuration ─────────────────────────────────────────────────────────────
# Load equipment catalogue generated by data_ingestion/extract_equipment.py
# Falls back to empty dict if the file doesn't exist yet.
_EQUIPMENT_JSON = os.path.join(
    os.path.dirname(__file__), "..", "data_ingestion", "equipment_by_division.json"
)
try:
    with open(_EQUIPMENT_JSON, encoding="utf-8") as _f:
        EQUIPMENT_CATALOGUE: dict = json.load(_f)
except FileNotFoundError:
    EQUIPMENT_CATALOGUE = {}

LLM_API_URL = os.getenv("LLM_API_URL", "http://localhost:8000")
APP_PORT    = int(os.getenv("APP_PORT", "8080"))

SECRET_KEY = os.getenv("SECRET_KEY", "your-very-secret-key-change-in-production")
ALGORITHM  = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 1 day

# ── App setup ─────────────────────────────────────────────────────────────────

logging.basicConfig(level=logging.INFO)

pwd_context = CryptContext(schemes=["bcrypt", "sha256_crypt"], deprecated="auto")

app = FastAPI(title="ProdAI — Plant RCA Dashboard")
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

# Include JSON API routes for React SPA
app.include_router(api_router)


# ── DB dependency ─────────────────────────────────────────────────────────────

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ── Auth helpers ──────────────────────────────────────────────────────────────

def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=15))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

def get_current_user_from_cookie(request: Request, db: Session = Depends(get_db)) -> Optional[User]:
    token = request.cookies.get("access_token")
    if not token:
        return None
    try:
        if token.startswith("Bearer "):
            token = token.split(" ", 1)[1]
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email: str = payload.get("sub")
        if not email:
            return None
    except jwt.PyJWTError:
        return None
    return db.query(User).filter(User.email == email).first()


# ── Startup: create tables + seed default users ───────────────────────────────

@app.on_event("startup")
async def startup_event():
    Base.metadata.create_all(bind=engine)

    # Ensure database schema is migrated (add component_name to breakdown_logs if missing)
    db_conn = engine.connect()
    has_col = False
    try:
        from sqlalchemy import text
        res = db_conn.execute(text("PRAGMA table_info(breakdown_logs);"))
        for row in res:
            if row[1] == "component_name":
                has_col = True
                break
    except Exception as e:
        print(f"Error checking breakdown_logs columns: {e}")
    
    if not has_col:
        try:
            db_conn.execute(text("ALTER TABLE breakdown_logs ADD COLUMN component_name VARCHAR;"))
            print("Successfully added component_name column to breakdown_logs table.")
        except Exception as e:
            print(f"Error adding component_name column: {e}")
    db_conn.close()

    db = SessionLocal()
    if not db.query(User).first():
        default_users = [
            User(email="admin@plant.com",   hashed_password=get_password_hash("admin123"), name="Admin",                division="Admin"),
            User(email="bnfc@plant.com",    hashed_password=get_password_hash("pass123"),  name="BNFC Manager",         division="BNFC"),
            User(email="pellet1@plant.com", hashed_password=get_password_hash("pass123"),  name="Pellet 1 Manager",     division="Pellet 1"),
            User(email="pellet2@plant.com", hashed_password=get_password_hash("pass123"),  name="Pellet 2 Manager",     division="Pellet 2"),
            User(email="sms1@plant.com",    hashed_password=get_password_hash("pass123"),  name="SMS 1 Manager",        division="SMS 1"),
            User(email="sms2@plant.com",    hashed_password=get_password_hash("pass123"),  name="SMS 2 Manager",        division="SMS 2"),
            User(email="dri1@plant.com",    hashed_password=get_password_hash("pass123"),  name="DRI 1 Manager",        division="DRI 1"),
            User(email="dri2@plant.com",    hashed_password=get_password_hash("pass123"),  name="DRI 2 Manager",        division="DRI 2"),
            User(email="cpp@plant.com",     hashed_password=get_password_hash("pass123"),  name="CPP Manager",          division="CPP"),
            User(email="cpp2@plant.com",    hashed_password=get_password_hash("pass123"),  name="CPP 2 Manager",        division="CPP 2"),
            User(email="pgp@plant.com",     hashed_password=get_password_hash("pass123"),  name="PGP Manager",          division="PGP"),
            User(email="fire@plant.com",    hashed_password=get_password_hash("pass123"),  name="Fire Service Manager", division="FIRE SERVICE"),
        ]
        db.add_all(default_users)
        db.commit()

    # Sync equipment from the catalogue and breakdown logs
    existing_equips = db.query(Equipment).all()
    existing_map = {(eq.name.strip().lower(), eq.category): eq for eq in existing_equips}
    
    seq = 1
    if existing_equips:
        seq = max(eq.id for eq in existing_equips) + 1
        
    # 1. Seed/Sync from updated catalogue
    if EQUIPMENT_CATALOGUE:
        for division, machines in sorted(EQUIPMENT_CATALOGUE.items()):
            for machine in sorted(set(machines)):
                if not machine or not machine.strip():
                    continue
                key = (machine.strip().lower(), division)
                if key not in existing_map:
                    new_eq = Equipment(
                        id=seq,
                        name=machine.strip(),
                        asset_tag=f"EQ-{seq:04d}",
                        category=division,
                        location=division,
                        criticality="Medium",
                        asset_health_score=100,
                    )
                    db.add(new_eq)
                    existing_map[key] = new_eq
                    seq += 1
        db.commit()
        
    # 2. Seed any unmatched machine names from BreakdownLog
    rows = db.query(BreakdownLog.division, BreakdownLog.machine_name).filter(
        BreakdownLog.machine_name != None,
        BreakdownLog.machine_name != "",
    ).distinct().all()
    
    # Refresh existing equips list
    all_equips = db.query(Equipment).all()
    
    def find_matching_equipment_in_list(m_name, division, eq_list):
        c_m = clean_equipment_name(m_name)
        if not c_m:
            return None
        div_equips = [e for e in eq_list if e.category == division]
        # Phase 1: Exact
        for e in div_equips:
            if clean_equipment_name(e.name) == c_m:
                return e
        # Phase 2: Substring
        sorted_div_equips = sorted(div_equips, key=lambda x: len(clean_equipment_name(x.name)), reverse=True)
        for e in sorted_div_equips:
            c_e = clean_equipment_name(e.name)
            if c_e in c_m:
                return e
        return None

    db_updated = False
    for division, machine_name in rows:
        if not division or not machine_name or not machine_name.strip():
            continue
        matched = find_matching_equipment_in_list(machine_name, division, all_equips)
        if not matched:
            new_eq = Equipment(
                id=seq,
                name=machine_name.strip(),
                asset_tag=f"EQ-{seq:04d}",
                category=division,
                location=division,
                criticality="Medium",
                asset_health_score=100,
            )
            db.add(new_eq)
            all_equips.append(new_eq)
            seq += 1
            db_updated = True
            
    if db_updated:
        db.commit()
    db.close()


# ── React SPA serving ─────────────────────────────────────────────────────────
SPA_DIR = os.path.join(os.path.dirname(__file__), "static", "spa")
SPA_ENABLED = os.path.isfile(os.path.join(SPA_DIR, "index.html"))

if SPA_ENABLED:
    _spa_assets = os.path.join(SPA_DIR, "assets")
    if os.path.isdir(_spa_assets):
        app.mount("/assets", StaticFiles(directory=_spa_assets), name="spa-assets")

def _serve_spa() -> HTMLResponse:
    """Read and return the React SPA index.html with no-cache headers."""
    with open(os.path.join(SPA_DIR, "index.html"), encoding="utf-8") as f:
        return HTMLResponse(
            content=f.read(),
            headers={"Cache-Control": "no-cache, no-store, must-revalidate", "Pragma": "no-cache"},
        )


# ── SPA-served routes ────────────────────────────────────────────────────────
# All pages whose UI is rendered by the React SPA. Every entry here just
# delegates to _serve_spa() — React Router handles the actual page logic.

if SPA_ENABLED:
    @app.get("/dashboard", response_class=HTMLResponse)
    async def dashboard_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/equipment", response_class=HTMLResponse)
    async def equipment_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/prodai", response_class=HTMLResponse)
    async def prodai_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/analytics", response_class=HTMLResponse)
    async def analytics_page(request: Request, db: Session = Depends(get_db)):
        return RedirectResponse(url="/prodai", status_code=status.HTTP_302_FOUND)

    @app.get("/beneficiation-pfd", response_class=HTMLResponse)
    async def beneficiation_pfd_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/log-breakdown", response_class=HTMLResponse)
    async def log_breakdown_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/capa/board", response_class=HTMLResponse)
    async def capa_board_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/capa/create", response_class=HTMLResponse)
    async def capa_create_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/capa/{capa_id}/detail", response_class=HTMLResponse)
    async def capa_detail_page(capa_id: int, request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()

    @app.get("/chat", response_class=HTMLResponse)
    async def chat_page(request: Request, db: Session = Depends(get_db)):
        user = get_current_user_from_cookie(request, db)
        if not user:
            return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
        return _serve_spa()


# ── Auth routes ───────────────────────────────────────────────────────────────


@app.get("/", response_class=HTMLResponse)
async def home_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if user:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    return templates.TemplateResponse("login.html", {"request": request})


@app.get("/login", response_class=HTMLResponse)
async def login_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if user:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    return templates.TemplateResponse("login.html", {"request": request})


@app.post("/login", response_class=HTMLResponse)
async def login_post(
    request: Request,
    email: str = Form(...),
    password: str = Form(...),
    db: Session = Depends(get_db),
):
    user = db.query(User).filter(User.email == email).first()
    if not user or not verify_password(password, user.hashed_password):
        return templates.TemplateResponse(
            "login.html",
            {"request": request, "error": "Incorrect email or password"},
            status_code=status.HTTP_401_UNAUTHORIZED,
        )
    token = create_access_token(
        data={"sub": user.email},
        expires_delta=timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES),
    )
    response = RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    response.set_cookie(key="access_token", value=f"Bearer {token}", httponly=True, max_age=86400)
    return response


@app.get("/logout")
async def logout():
    response = RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    response.delete_cookie(key="access_token")
    return response


# ── Signup ────────────────────────────────────────────────────────────────────

DIVISIONS = [
    "BNFC", "Pellet 1", "Pellet 2", "SMS 1", "SMS 2",
    "DRI 1", "DRI 2", "CPP", "CPP 2", "PGP", "FIRE SERVICE",
]

@app.get("/signup", response_class=HTMLResponse)
async def signup_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if user:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    return templates.TemplateResponse("signup.html", {"request": request, "divisions": DIVISIONS})


@app.post("/signup", response_class=HTMLResponse)
async def signup_post(
    request: Request,
    name: str = Form(...),
    email: str = Form(...),
    password: str = Form(...),
    confirm_password: str = Form(...),
    division: str = Form(...),
    db: Session = Depends(get_db),
):
    errors = {}
    # Validate
    if len(name.strip()) < 2:
        errors["name"] = "Name must be at least 2 characters."
    if len(password) < 6:
        errors["password"] = "Password must be at least 6 characters."
    if password != confirm_password:
        errors["confirm_password"] = "Passwords do not match."
    if division not in DIVISIONS:
        errors["division"] = "Please select a valid division."

    # Check if email already exists
    existing = db.query(User).filter(User.email == email).first()
    if existing:
        errors["email"] = "An account with this email already exists."

    if errors:
        return templates.TemplateResponse(
            "signup.html",
            {
                "request": request,
                "divisions": DIVISIONS,
                "errors": errors,
                "form_name": name,
                "form_email": email,
                "form_division": division,
            },
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        )

    new_user = User(
        email=email.strip().lower(),
        hashed_password=get_password_hash(password),
        name=name.strip(),
        division=division,
    )
    db.add(new_user)
    db.commit()

    # Auto-login after signup
    token = create_access_token(
        data={"sub": new_user.email},
        expires_delta=timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES),
    )
    response = RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    response.set_cookie(key="access_token", value=f"Bearer {token}", httponly=True, max_age=86400)
    return response


# ── Admin: Registered Users ──────────────────────────────────────────────────

@app.get("/admin/users", response_class=HTMLResponse)
async def admin_users_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    if user.division != "Admin":
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)

    users = db.query(User).order_by(User.id).all()
    return templates.TemplateResponse("admin_users.html", {
        "request": request,
        "user": user,
        "users": users,
        "active_page": "admin-users",
    })


# ── Log Breakdown ─────────────────────────────────────────────────────────────

@app.post("/log-breakdown")
async def log_breakdown_post(
    request: Request,
    division: str = Form(...),
    machine_name: str = Form(...),
    component_name: Optional[str] = Form(None),
    start_time: str = Form(...),
    end_time: Optional[str] = Form(None),
    feed_loss: bool = Form(False),
    description: str = Form(...),
    attached_doc_desc: Optional[str] = Form(None),
    attached_doc: Optional[UploadFile] = File(None),
    downtime_minutes: int = Form(0),
    revenue_loss: float = Form(0.0),
    severity_level: Optional[str] = Form(None),
    failure_type: Optional[str] = Form(None),
    action: Optional[str] = Form(None),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    doc_path = None
    if attached_doc and attached_doc.filename:
        os.makedirs("static/uploads", exist_ok=True)
        file_location = f"static/uploads/{attached_doc.filename}"
        with open(file_location, "wb+") as f:
            f.write(attached_doc.file.read())
        doc_path = file_location

    st_time = dateparser.parse(start_time) if start_time else None
    ed_time = dateparser.parse(end_time)   if end_time   else None

    # Auto-compute MTTR in hours from downtime
    mttr_h = round(downtime_minutes / 60, 1) if downtime_minutes and downtime_minutes > 0 else None

    new_log = BreakdownLog(
        machine_name=machine_name,
        component_name=component_name if component_name else None,
        division=division,
        description=description,
        downtime_minutes=downtime_minutes,
        status="Open",
        author_id=user.id,
        start_time=st_time,
        end_time=ed_time,
        feed_loss=feed_loss,
        attached_doc=doc_path,
        doc_description=attached_doc_desc,
        revenue_loss=revenue_loss,
        mttr_hours=mttr_h,
        severity_level=severity_level if severity_level else None,
        failure_type=failure_type if failure_type else None,
    )
    db.add(new_log)
    db.commit()
    db.refresh(new_log)

    # Route based on which button was pressed
    if action == "rca_ai":
        return RedirectResponse(url=f"/create-rca/{new_log.id}?ai=true", status_code=status.HTTP_302_FOUND)
    elif action == "create_rca":
        return RedirectResponse(url=f"/create-rca/{new_log.id}", status_code=status.HTTP_302_FOUND)
    return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)


# ── Create / View RCA ─────────────────────────────────────────────────────────


def _extract_pdf_text(pdf_path: str) -> str:
    """Extract text from a PDF file using PyPDF2. Returns extracted text (max 10k chars)."""
    try:
        from PyPDF2 import PdfReader
        reader = PdfReader(pdf_path)
        text_parts = []
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text_parts.append(page_text.strip())
        full_text = "\n\n".join(text_parts)
        # Cap at 10,000 chars to avoid overwhelming LLM context
        if len(full_text) > 10000:
            full_text = full_text[:10000] + "\n...[truncated]"
        return full_text
    except Exception as e:
        logging.error(f"PDF text extraction failed for {pdf_path}: {e}")
        return ""

@app.get("/create-rca/{log_id}", response_class=HTMLResponse)
async def create_rca_page(
    log_id: int,
    request: Request,
    ai: bool = Query(default=False),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    log = db.query(BreakdownLog).filter(BreakdownLog.id == log_id).first()
    if not log:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)

    # Determine saved RCA type
    rca_type = None
    rca_data_json = "null"
    if log.rca_data and log.rca_data not in ("[]", "null", ""):
        try:
            parsed = json.loads(log.rca_data)
            if isinstance(parsed, list):
                rca_type = "manual_tree"  # legacy raw-array format
            else:
                rca_type = parsed.get("type", "manual_tree")
            rca_data_json = log.rca_data
        except (json.JSONDecodeError, AttributeError):
            pass

    # Format times for JS consumption
    start_iso = log.start_time.isoformat() if log.start_time else ""
    end_iso   = log.end_time.isoformat()   if log.end_time   else ""

    # Check if an image is attached (image extensions)
    image_extensions = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}
    pdf_extensions = {'.pdf'}
    attached_image_url = None
    attached_image_path = None
    attached_pdf_text = None
    if log.attached_doc:
        ext = os.path.splitext(log.attached_doc)[1].lower()
        if ext in image_extensions:
            attached_image_url = "/" + log.attached_doc.replace("\\", "/")
            # Absolute path for backend image analysis
            attached_image_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                log.attached_doc
            )
        elif ext in pdf_extensions:
            # Extract text from uploaded PDF
            pdf_abs_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                log.attached_doc
            )
            attached_pdf_text = _extract_pdf_text(pdf_abs_path)

    return templates.TemplateResponse("create_rca.html", {
        "request":       request,
        "user":          user,
        "log":           log,
        "rca_data_json": rca_data_json,
        "rca_type":      rca_type,
        "auto_start_ai": ai,
        "llm_api_url":   LLM_API_URL,
        "start_iso":     start_iso,
        "end_iso":       end_iso,
        "attached_image_url": attached_image_url,
        "attached_image_path": attached_image_path,
        "image_description": log.doc_description or "",
        "attached_pdf_text": attached_pdf_text or "",
        "active_page": "",
    })


@app.post("/save-rca/{log_id}")
async def save_rca_post(
    log_id: int,
    request: Request,
    rca_data: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    log = db.query(BreakdownLog).filter(BreakdownLog.id == log_id).first()
    if log:
        log.rca_data = rca_data
        db.commit()

    return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)


@app.post("/update-status/{log_id}")
async def update_status(
    log_id: int,
    request: Request,
    new_status: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    log = db.query(BreakdownLog).filter(BreakdownLog.id == log_id).first()
    if log:
        log.status = new_status
        db.commit()

    return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)


# ── CAPA Board ────────────────────────────────────────────────────────────────

@app.post("/capa/create")
async def capa_create_post(
    request: Request,
    action_type: str = Form("Corrective"),
    actions: str = Form(""),
    owner: str = Form(""),
    due_date: str = Form(""),
    priority: str = Form(""),
    impact_level: str = Form(""),
    capa_status: str = Form("Open"),
    root_cause: str = Form(""),
    breakdown_id: Optional[int] = Form(None),
    edit_id: Optional[int] = Form(None),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    normalized_owner = normalize_full_owner_string(owner)

    if edit_id:
        capa = db.query(CAPA).filter(CAPA.id == edit_id).first()
        if capa:
            capa.action_type = action_type
            capa.actions = actions
            capa.owner = normalized_owner
            capa.due_date = due_date
            capa.priority = priority
            capa.impact_level = impact_level
            capa.status = capa_status
            capa.root_cause = root_cause
    else:
        capa = CAPA(
            breakdown_log_id=breakdown_id,
            action_type=action_type,
            actions=actions,
            owner=normalized_owner,
            due_date=due_date,
            priority=priority,
            impact_level=impact_level,
            status=capa_status,
            root_cause=root_cause,
        )
        db.add(capa)

    db.commit()
    return RedirectResponse(url="/capa/board", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/status")
async def capa_update_status(
    capa_id: int,
    request: Request,
    new_status: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    capa = db.query(CAPA).filter(CAPA.id == capa_id).first()
    if capa:
        capa.status = new_status
        db.commit()

    return RedirectResponse(url="/capa/board", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/task")
async def capa_add_task(
    capa_id: int,
    request: Request,
    task_title: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    task = CAPATask(capa_id=capa_id, task_title=task_title)
    db.add(task)
    db.commit()
    return RedirectResponse(url=f"/capa/{capa_id}/detail", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/task/{task_id}/toggle")
async def capa_toggle_task(
    capa_id: int,
    task_id: int,
    request: Request,
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    task = db.query(CAPATask).filter(CAPATask.id == task_id).first()
    if task:
        task.is_completed = not task.is_completed
        db.commit()
    return RedirectResponse(url=f"/capa/{capa_id}/detail", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/comment")
async def capa_add_comment(
    capa_id: int,
    request: Request,
    comment_text: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    comment = CAPAComment(capa_id=capa_id, comment_text=comment_text, author_name=user.name)
    db.add(comment)
    db.commit()
    return RedirectResponse(url=f"/capa/{capa_id}/detail", status_code=status.HTTP_302_FOUND)


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=APP_PORT)
