import os
import json
import logging
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from typing import Optional

import jwt
from fastapi import FastAPI, Depends, HTTPException, Request, Response, Form, status, UploadFile, File, Query
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from passlib.context import CryptContext
from sqlalchemy.orm import Session
from dateutil import parser as dateparser

from database import engine, SessionLocal, User, BreakdownLog, CAPA, CAPATask, CAPAComment, Base
from api_routes import router as api_router

# ── Configuration ─────────────────────────────────────────────────────────────
# Load equipment catalogue generated by data_ingestion/extract_equipment.py
# Falls back to empty dict if the file doesn't exist yet.
_EQUIPMENT_JSON = os.path.join(
    os.path.dirname(__file__), "..", "data_ingestion", "equipment_by_division.json"
)
try:
    with open(_EQUIPMENT_JSON, encoding="utf-8") as _f:
        EQUIPMENT_CATALOGUE: dict = json.load(_f)
except FileNotFoundError:
    EQUIPMENT_CATALOGUE = {}

LLM_API_URL = os.getenv("LLM_API_URL", "http://localhost:8000")
APP_PORT    = int(os.getenv("APP_PORT", "8080"))

SECRET_KEY = os.getenv("SECRET_KEY", "your-very-secret-key-change-in-production")
ALGORITHM  = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 1 day

# ── App setup ─────────────────────────────────────────────────────────────────

logging.basicConfig(level=logging.INFO)

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

app = FastAPI(title="ProdAI — Plant RCA Dashboard")
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

# Include JSON API routes for React SPA
app.include_router(api_router)


# ── DB dependency ─────────────────────────────────────────────────────────────

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ── Auth helpers ──────────────────────────────────────────────────────────────

def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=15))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

def get_current_user_from_cookie(request: Request, db: Session = Depends(get_db)) -> Optional[User]:
    token = request.cookies.get("access_token")
    if not token:
        return None
    try:
        if token.startswith("Bearer "):
            token = token.split(" ", 1)[1]
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email: str = payload.get("sub")
        if not email:
            return None
    except jwt.PyJWTError:
        return None
    return db.query(User).filter(User.email == email).first()


# ── Startup: create tables + seed default users ───────────────────────────────

@app.on_event("startup")
async def startup_event():
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    if not db.query(User).first():
        default_users = [
            User(email="admin@plant.com",   hashed_password=get_password_hash("admin123"), name="Admin",                division="Admin"),
            User(email="bnfc@plant.com",    hashed_password=get_password_hash("pass123"),  name="BNFC Manager",         division="BNFC"),
            User(email="pellet1@plant.com", hashed_password=get_password_hash("pass123"),  name="Pellet 1 Manager",     division="Pellet 1"),
            User(email="pellet2@plant.com", hashed_password=get_password_hash("pass123"),  name="Pellet 2 Manager",     division="Pellet 2"),
            User(email="sms1@plant.com",    hashed_password=get_password_hash("pass123"),  name="SMS 1 Manager",        division="SMS 1"),
            User(email="sms2@plant.com",    hashed_password=get_password_hash("pass123"),  name="SMS 2 Manager",        division="SMS 2"),
            User(email="dri1@plant.com",    hashed_password=get_password_hash("pass123"),  name="DRI 1 Manager",        division="DRI 1"),
            User(email="dri2@plant.com",    hashed_password=get_password_hash("pass123"),  name="DRI 2 Manager",        division="DRI 2"),
            User(email="cpp@plant.com",     hashed_password=get_password_hash("pass123"),  name="CPP Manager",          division="CPP"),
            User(email="cpp2@plant.com",    hashed_password=get_password_hash("pass123"),  name="CPP 2 Manager",        division="CPP 2"),
            User(email="pgp@plant.com",     hashed_password=get_password_hash("pass123"),  name="PGP Manager",          division="PGP"),
            User(email="fire@plant.com",    hashed_password=get_password_hash("pass123"),  name="Fire Service Manager", division="FIRE SERVICE"),
        ]
        db.add_all(default_users)
        db.commit()
    db.close()


# ── React SPA serving ─────────────────────────────────────────────────────────
SPA_DIR = os.path.join(os.path.dirname(__file__), "static", "spa")
SPA_ENABLED = os.path.isfile(os.path.join(SPA_DIR, "index.html"))

if SPA_ENABLED:
    _spa_assets = os.path.join(SPA_DIR, "assets")
    if os.path.isdir(_spa_assets):
        app.mount("/assets", StaticFiles(directory=_spa_assets), name="spa-assets")

def _serve_spa() -> HTMLResponse:
    """Read and return the React SPA index.html with no-cache headers."""
    with open(os.path.join(SPA_DIR, "index.html"), encoding="utf-8") as f:
        return HTMLResponse(
            content=f.read(),
            headers={"Cache-Control": "no-cache, no-store, must-revalidate", "Pragma": "no-cache"},
        )

# ── Auth routes ───────────────────────────────────────────────────────────────


@app.get("/", response_class=HTMLResponse)
async def home_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if user:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()
    return templates.TemplateResponse("login.html", {"request": request})


@app.get("/login", response_class=HTMLResponse)
async def login_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if user:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()
    return templates.TemplateResponse("login.html", {"request": request})


@app.post("/login", response_class=HTMLResponse)
async def login_post(
    request: Request,
    email: str = Form(...),
    password: str = Form(...),
    db: Session = Depends(get_db),
):
    user = db.query(User).filter(User.email == email).first()
    if not user or not verify_password(password, user.hashed_password):
        return templates.TemplateResponse(
            "login.html",
            {"request": request, "error": "Incorrect email or password"},
            status_code=status.HTTP_401_UNAUTHORIZED,
        )
    token = create_access_token(
        data={"sub": user.email},
        expires_delta=timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES),
    )
    response = RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)
    response.set_cookie(key="access_token", value=f"Bearer {token}", httponly=True, max_age=86400)
    return response


@app.get("/logout")
async def logout():
    response = RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    response.delete_cookie(key="access_token")
    return response


# ── Dashboard ─────────────────────────────────────────────────────────────────

@app.get("/dashboard", response_class=HTMLResponse)
async def dashboard_page(
    request: Request,
    machine: Optional[str] = None,
    division: Optional[str] = None,
    date_filter: Optional[str] = None,
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()

    query = db.query(BreakdownLog)
    if user.division != "Admin":
        query = query.filter(BreakdownLog.division == user.division)

    # Dropdown options
    all_machines = sorted([
        m[0] for m in query.with_entities(BreakdownLog.machine_name)
        .filter(BreakdownLog.machine_name != None, BreakdownLog.machine_name != "")
        .distinct().all()
    ])
    all_divisions = sorted([
        d[0] for d in query.with_entities(BreakdownLog.division)
        .filter(BreakdownLog.division != None, BreakdownLog.division != "")
        .distinct().all()
    ])

    # Filters
    if machine and machine != "All":
        query = query.filter(BreakdownLog.machine_name == machine)
    if division and division != "All":
        query = query.filter(BreakdownLog.division == division)

    now = datetime.utcnow()
    if date_filter == "Last 7 Days":
        query = query.filter(BreakdownLog.logged_at >= now - timedelta(days=7))
    elif date_filter == "Last 30 Days":
        query = query.filter(BreakdownLog.logged_at >= now - timedelta(days=30))
    elif date_filter == "This Month":
        query = query.filter(BreakdownLog.logged_at >= datetime(now.year, now.month, 1))
    elif date_filter == "Last Month":
        last_end   = datetime(now.year, now.month, 1) - timedelta(days=1)
        last_start = datetime(last_end.year, last_end.month, 1)
        query = query.filter(BreakdownLog.logged_at >= last_start,
                             BreakdownLog.logged_at <= last_end + timedelta(days=1, microseconds=-1))

    logs = query.order_by(BreakdownLog.logged_at.desc()).all()

    total_breakdowns = len(logs)
    total_downtime   = sum(log.downtime_minutes or 0 for log in logs)
    avg_downtime     = round(total_downtime / total_breakdowns, 1) if total_breakdowns else 0
    resolved_count   = len([l for l in logs if l.status in ("Resolved", "Completed")])

    # ── KPIs matching RAG_april ──────────────────────────────────
    open_breakdowns = len([l for l in logs if l.status in ("Open", "In Progress")])

    # CAPA overdue count
    capa_overdue = db.query(CAPA).filter(
        CAPA.status.notin_(["Completed"]),
        CAPA.due_date != None,
        CAPA.due_date != "",
        CAPA.due_date < datetime.utcnow().strftime("%Y-%m-%d"),
    ).count()

    # Avg MTTR from logs that have mttr_hours set, or compute from downtime
    mttr_values = []
    for log in logs:
        if log.mttr_hours is not None:
            mttr_values.append(log.mttr_hours)
        elif log.downtime_minutes and log.downtime_minutes > 0 and log.status in ("Resolved", "Completed"):
            mttr_values.append(round(log.downtime_minutes / 60, 1))
    avg_mttr = round(sum(mttr_values) / len(mttr_values), 1) if mttr_values else None

    # ── Top 5 failing equipment ──────────────────────────────────
    machine_counts = Counter(log.machine_name for log in logs if log.machine_name)
    top_equipment = []
    for equip_name, count in machine_counts.most_common(5):
        # Find division for this equipment
        sample = next((l for l in logs if l.machine_name == equip_name), None)
        top_equipment.append({
            "equipment_name": equip_name,
            "breakdown_count": count,
            "category": sample.division if sample else "Unknown",
        })

    # ── Failures by division (for pie chart) ─────────────────────
    division_counts = Counter(log.division for log in logs if log.division)
    failures_by_category = [
        {"category": div, "count": cnt}
        for div, cnt in division_counts.most_common(8)
    ]

    # ── MTTR trend (monthly) ─────────────────────────────────────
    mttr_trend = []
    monthly_mttr = defaultdict(list)
    for log in logs:
        if log.logged_at:
            month_key = log.logged_at.strftime("%b %Y")
            mttr_val = None
            if log.mttr_hours is not None:
                mttr_val = log.mttr_hours
            elif log.downtime_minutes and log.downtime_minutes > 0 and log.status in ("Resolved", "Completed"):
                mttr_val = round(log.downtime_minutes / 60, 1)
            if mttr_val is not None:
                monthly_mttr[month_key].append(mttr_val)

    # Sort by date and take last 12 months
    now = datetime.utcnow()
    for i in range(11, -1, -1):
        d = now - timedelta(days=i * 30)
        mk = d.strftime("%b %Y")
        if mk in monthly_mttr:
            vals = monthly_mttr[mk]
            mttr_trend.append({"month": mk, "avgMttr": round(sum(vals) / len(vals), 1)})

    # ── RCA Reports (from breakdown logs that have rca_data) ─────
    rca_reports = []
    for log in logs:
        if log.rca_data and log.rca_data not in ("[]", "null", ""):
            try:
                parsed = json.loads(log.rca_data)
                root_cause = ""
                corrective_action = ""
                if isinstance(parsed, dict):
                    root_cause = parsed.get("final_root_cause", "")
                    # Get first CAPA action if available
                    capa_list = parsed.get("capa", [])
                    if capa_list and isinstance(capa_list, list) and len(capa_list) > 0:
                        corrective_action = capa_list[0].get("action", "")
                if root_cause:
                    rca_reports.append({
                        "id": log.id,
                        "equipment_name": log.machine_name,
                        "root_cause": root_cause,
                        "corrective_action": corrective_action,
                        "created_at": log.logged_at,
                        "author": log.author.name if log.author else "Unknown",
                    })
            except (json.JSONDecodeError, AttributeError):
                pass
        if len(rca_reports) >= 6:
            break

    machines_chart = {}
    for log in logs:
        machines_chart[log.machine_name] = machines_chart.get(log.machine_name, 0) + 1

    return templates.TemplateResponse("dashboard.html", {
        "request": request,
        "user": user,
        "logs": logs,
        "total_breakdowns": total_breakdowns,
        "total_downtime": total_downtime,
        "avg_downtime": avg_downtime,
        "resolved_count": resolved_count,
        "machines": machines_chart,
        "all_machines": all_machines,
        "all_divisions": all_divisions,
        "selected_machine": machine or "All",
        "selected_division": division or "All",
        "selected_date": date_filter or "All Time",
        "active_page": "dashboard",
        # New RAG_april data
        "open_breakdowns": open_breakdowns,
        "capa_overdue": capa_overdue,
        "avg_mttr": avg_mttr,
        "top_equipment": top_equipment,
        "failures_by_category": failures_by_category,
        "mttr_trend": mttr_trend,
        "rca_reports": rca_reports,
    })


# ── Log Breakdown ─────────────────────────────────────────────────────────────

@app.get("/log-breakdown", response_class=HTMLResponse)
async def log_breakdown_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()

    # Start from the static catalogue so the dropdown is always pre-populated
    division_machines: dict = {k: list(v) for k, v in EQUIPMENT_CATALOGUE.items()}

    # Merge any additional machine names that users have logged over time
    rows = db.query(BreakdownLog.division, BreakdownLog.machine_name).filter(
        BreakdownLog.machine_name != None,
        BreakdownLog.machine_name != "",
    ).distinct().all()
    for div, machine in rows:
        if div and machine and machine.strip():
            division_machines.setdefault(div, [])
            if machine.strip() not in division_machines[div]:
                division_machines[div].append(machine.strip())
    for div in division_machines:
        division_machines[div] = sorted(division_machines[div])

    return templates.TemplateResponse("log_breakdown.html", {
        "request": request,
        "user": user,
        "division_machines_json": json.dumps(division_machines),
        "active_page": "log-issue",
    })


@app.post("/log-breakdown")
async def log_breakdown_post(
    request: Request,
    division: str = Form(...),
    machine_name: str = Form(...),
    start_time: str = Form(...),
    end_time: Optional[str] = Form(None),
    feed_loss: bool = Form(False),
    description: str = Form(...),
    attached_doc_desc: Optional[str] = Form(None),
    attached_doc: Optional[UploadFile] = File(None),
    downtime_minutes: int = Form(0),
    revenue_loss: float = Form(0.0),
    severity_level: Optional[str] = Form(None),
    failure_type: Optional[str] = Form(None),
    action: Optional[str] = Form(None),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    doc_path = None
    if attached_doc and attached_doc.filename:
        os.makedirs("static/uploads", exist_ok=True)
        file_location = f"static/uploads/{attached_doc.filename}"
        with open(file_location, "wb+") as f:
            f.write(attached_doc.file.read())
        doc_path = file_location

    st_time = dateparser.parse(start_time) if start_time else None
    ed_time = dateparser.parse(end_time)   if end_time   else None

    # Auto-compute MTTR in hours from downtime
    mttr_h = round(downtime_minutes / 60, 1) if downtime_minutes and downtime_minutes > 0 else None

    new_log = BreakdownLog(
        machine_name=machine_name,
        division=division,
        description=description,
        downtime_minutes=downtime_minutes,
        status="Open",
        author_id=user.id,
        start_time=st_time,
        end_time=ed_time,
        feed_loss=feed_loss,
        attached_doc=doc_path,
        doc_description=attached_doc_desc,
        revenue_loss=revenue_loss,
        mttr_hours=mttr_h,
        severity_level=severity_level if severity_level else None,
        failure_type=failure_type if failure_type else None,
    )
    db.add(new_log)
    db.commit()
    db.refresh(new_log)

    # Route based on which button was pressed
    if action == "rca_ai":
        return RedirectResponse(url=f"/create-rca/{new_log.id}?ai=true", status_code=status.HTTP_302_FOUND)
    elif action == "create_rca":
        return RedirectResponse(url=f"/create-rca/{new_log.id}", status_code=status.HTTP_302_FOUND)
    return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)


# ── Create / View RCA ─────────────────────────────────────────────────────────

@app.get("/create-rca/{log_id}", response_class=HTMLResponse)
async def create_rca_page(
    log_id: int,
    request: Request,
    ai: bool = Query(default=False),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    log = db.query(BreakdownLog).filter(BreakdownLog.id == log_id).first()
    if not log:
        return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)

    # Determine saved RCA type
    rca_type = None
    rca_data_json = "null"
    if log.rca_data and log.rca_data not in ("[]", "null", ""):
        try:
            parsed = json.loads(log.rca_data)
            if isinstance(parsed, list):
                rca_type = "manual_tree"  # legacy raw-array format
            else:
                rca_type = parsed.get("type", "manual_tree")
            rca_data_json = log.rca_data
        except (json.JSONDecodeError, AttributeError):
            pass

    # Format times for JS consumption
    start_iso = log.start_time.isoformat() if log.start_time else ""
    end_iso   = log.end_time.isoformat()   if log.end_time   else ""

    # Check if an image is attached (image extensions)
    image_extensions = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}
    attached_image_url = None
    attached_image_path = None
    if log.attached_doc:
        ext = os.path.splitext(log.attached_doc)[1].lower()
        if ext in image_extensions:
            attached_image_url = "/" + log.attached_doc.replace("\\", "/")
            # Absolute path for backend image analysis
            attached_image_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                log.attached_doc
            )

    return templates.TemplateResponse("create_rca.html", {
        "request":       request,
        "user":          user,
        "log":           log,
        "rca_data_json": rca_data_json,
        "rca_type":      rca_type,
        "auto_start_ai": ai,
        "llm_api_url":   LLM_API_URL,
        "start_iso":     start_iso,
        "end_iso":       end_iso,
        "attached_image_url": attached_image_url,
        "attached_image_path": attached_image_path,
        "image_description": log.doc_description or "",
        "active_page": "",
    })


@app.post("/save-rca/{log_id}")
async def save_rca_post(
    log_id: int,
    request: Request,
    rca_data: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    log = db.query(BreakdownLog).filter(BreakdownLog.id == log_id).first()
    if log:
        log.rca_data = rca_data
        db.commit()

    return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)


@app.post("/update-status/{log_id}")
async def update_status(
    log_id: int,
    request: Request,
    new_status: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    log = db.query(BreakdownLog).filter(BreakdownLog.id == log_id).first()
    if log:
        log.status = new_status
        db.commit()

    return RedirectResponse(url="/dashboard", status_code=status.HTTP_302_FOUND)


# ── CAPA Board ────────────────────────────────────────────────────────────────

@app.get("/capa/board", response_class=HTMLResponse)
async def capa_board_page(request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()

    capas = db.query(CAPA).order_by(CAPA.created_at.desc()).all()
    return templates.TemplateResponse("capa_board.html", {
        "request": request,
        "user": user,
        "capas": capas,
        "active_page": "capa-board",
    })


@app.get("/capa/create", response_class=HTMLResponse)
async def capa_create_page(
    request: Request,
    edit: Optional[int] = None,
    breakdown_id: Optional[int] = None,
    root_cause: Optional[str] = None,
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()

    capa = None
    if edit:
        capa = db.query(CAPA).filter(CAPA.id == edit).first()

    return templates.TemplateResponse("capa_create.html", {
        "request": request,
        "user": user,
        "capa": capa,
        "breakdown_id": breakdown_id,
        "root_cause": root_cause or (capa.root_cause if capa else ""),
        "active_page": "",
    })


@app.post("/capa/create")
async def capa_create_post(
    request: Request,
    action_type: str = Form("Corrective"),
    actions: str = Form(""),
    owner: str = Form(""),
    due_date: str = Form(""),
    priority: str = Form(""),
    impact_level: str = Form(""),
    capa_status: str = Form("Open"),
    root_cause: str = Form(""),
    breakdown_id: Optional[int] = Form(None),
    edit_id: Optional[int] = Form(None),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    if edit_id:
        capa = db.query(CAPA).filter(CAPA.id == edit_id).first()
        if capa:
            capa.action_type = action_type
            capa.actions = actions
            capa.owner = owner
            capa.due_date = due_date
            capa.priority = priority
            capa.impact_level = impact_level
            capa.status = capa_status
            capa.root_cause = root_cause
    else:
        capa = CAPA(
            breakdown_log_id=breakdown_id,
            action_type=action_type,
            actions=actions,
            owner=owner,
            due_date=due_date,
            priority=priority,
            impact_level=impact_level,
            status=capa_status,
            root_cause=root_cause,
        )
        db.add(capa)

    db.commit()
    return RedirectResponse(url="/capa/board", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/status")
async def capa_update_status(
    capa_id: int,
    request: Request,
    new_status: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    capa = db.query(CAPA).filter(CAPA.id == capa_id).first()
    if capa:
        capa.status = new_status
        db.commit()

    return RedirectResponse(url="/capa/board", status_code=status.HTTP_302_FOUND)


# ── CAPA Detail ──────────────────────────────────────────────────────────────

@app.get("/capa/{capa_id}/detail", response_class=HTMLResponse)
async def capa_detail_page(capa_id: int, request: Request, db: Session = Depends(get_db)):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
    if SPA_ENABLED:
        return _serve_spa()

    capa = db.query(CAPA).filter(CAPA.id == capa_id).first()
    if not capa:
        return RedirectResponse(url="/capa/board", status_code=status.HTTP_302_FOUND)

    tasks = db.query(CAPATask).filter(CAPATask.capa_id == capa_id).order_by(CAPATask.id).all()
    comments = db.query(CAPAComment).filter(CAPAComment.capa_id == capa_id).order_by(CAPAComment.created_at).all()

    action_steps = [s for s in (capa.actions or "").split("\n") if s.strip()]

    return templates.TemplateResponse("capa_detail.html", {
        "request": request,
        "user": user,
        "capa": capa,
        "tasks": tasks,
        "comments": comments,
        "action_steps": action_steps,
        "active_page": "",
    })


@app.post("/capa/{capa_id}/task")
async def capa_add_task(
    capa_id: int,
    request: Request,
    task_title: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    task = CAPATask(capa_id=capa_id, task_title=task_title)
    db.add(task)
    db.commit()
    return RedirectResponse(url=f"/capa/{capa_id}/detail", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/task/{task_id}/toggle")
async def capa_toggle_task(
    capa_id: int,
    task_id: int,
    request: Request,
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    task = db.query(CAPATask).filter(CAPATask.id == task_id).first()
    if task:
        task.is_completed = not task.is_completed
        db.commit()
    return RedirectResponse(url=f"/capa/{capa_id}/detail", status_code=status.HTTP_302_FOUND)


@app.post("/capa/{capa_id}/comment")
async def capa_add_comment(
    capa_id: int,
    request: Request,
    comment_text: str = Form(...),
    db: Session = Depends(get_db),
):
    user = get_current_user_from_cookie(request, db)
    if not user:
        return RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)

    comment = CAPAComment(capa_id=capa_id, comment_text=comment_text, author_name=user.name)
    db.add(comment)
    db.commit()
    return RedirectResponse(url=f"/capa/{capa_id}/detail", status_code=status.HTTP_302_FOUND)


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=APP_PORT)
